version: '3.8'

services:
  neo4j:
    container_name: ${CONTAINER_NAME:-neo4j-safeai}
    image: neo4j:${NEO4J_VERSION:-5.15.0}
    ports:
      - "${HTTP_PORT:-7474}:7474"
      - "${BOLT_PORT:-7687}:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,safeai.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*,safeai.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./neo4j-plugins:/plugins
      - ./config:/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  gui:
    container_name: safeai-gui
    build:
      context: ../safeAI-gui
      dockerfile: Dockerfile
    ports:
      - "${GUI_PORT:-3001}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${HTTP_PORT:-7474}
      - REACT_APP_OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_BLOCKCHAIN_ENDPOINT=${BLOCKCHAIN_ENDPOINT}
      - REACT_APP_ADMIN_WALLET_KEY=${ADMIN_WALLET_KEY}
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

  docs:
    container_name: safeai-docs
    build:
      context: ../docs
      dockerfile: Dockerfile
    ports:
      - "${DOCS_PORT:-8080}:8080"
    volumes:
      - ../docs:/app
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
