version: '3.8'

services:
  neo4j:
    container_name: neo4j-safeai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-7474}:7474"
      - "${BOLT_PORT:-7687}:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,safeai.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,safeai.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    restart: unless-stopped

  gui:
    container_name: safeai-gui
    build:
      context: ../safeAI-gui
      dockerfile: Dockerfile
    ports:
      - "${GUI_PORT:-3001}:3001"
      - "8545:8545"
    environment:
      - REACT_APP_API_URL=http://localhost:${HTTP_PORT:-7474}
      - REACT_APP_OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_BLOCKCHAIN_ENDPOINT=http://localhost:8545
      - REACT_APP_ADMIN_WALLET_KEY=${ADMIN_WALLET_KEY}
    depends_on:
      neo4j:
        condition: service_started
    restart: unless-stopped

  docs:
    container_name: safeai-docs
    build:
      context: ../docs
      dockerfile: Dockerfile
    ports:
      - "${DOCS_PORT:-8080}:80"
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
