version: "3.8"

services:
  neo4j:
    image: neo4j:5.9
    container_name: neo4j-safeai
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_security_procedures_unrestricted=*
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_directories_plugins=/plugins
    volumes:
      - ./neo4j-plugins:/plugins
    restart: on-failure
