version: "3.8"

services:
  neo4j:
    image: neo4j:5.9
    container_name: neo4j-safeai
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_dbms_security_procedures_unrestricted=*
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_directories_plugins=/plugins
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_WALLET_KEY=${ADMIN_WALLET_KEY}
      - BLOCKCHAIN_ENDPOINT=${BLOCKCHAIN_ENDPOINT:-http://host.docker.internal:7545}
      - SAFEAI_API_KEY=${SAFEAI_API_KEY}
    volumes:
      - ./neo4j-plugins:/plugins
      - ./config:/conf
    restart: on-failure
