version: '3.8'

services:
  gui:
    container_name: safeai-gui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GUI_PORT:-3001}:80"
    environment:
      - REACT_APP_API_URL=http://localhost:${HTTP_PORT:-7474}
      - REACT_APP_OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_BLOCKCHAIN_ENDPOINT=${BLOCKCHAIN_ENDPOINT}
      - REACT_APP_ADMIN_WALLET_KEY=${ADMIN_WALLET_KEY}
    restart: unless-stopped

  docs:
    container_name: safeai-docs
    build:
      context: ../docs
      dockerfile: Dockerfile
    ports:
      - "${DOCS_PORT:-8080}:80"
    restart: unless-stopped

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:

networks:
  safeai-network:
    driver: bridge 